site_title = "vss docs"
site_description = "vss document site"
base_url = "https://vss.veltiosoft.dev"

[build]
ignore_files = ["README.md"]

[build.markdown]
allow_dangerous_html = false

[build.tags]
enable = true
template = "tags/default.html"
url_pattern = "/tags/{tag}/"
